# Generated by Django 4.2.4 on 2023-08-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('biography', models.TextField()),
                ('birth', models.DateField()),
                ('death', models.DateField()),
                ('nationality', models.CharField(max_length=255)),
                ('awards', models.TextField()),
            ],
        ),
    ]
