# Generated by Django 4.2.4 on 2023-08-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
